default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch('RAILS_MAX_THREADS') { 5 }.to_i %>
  timeout: 5000
  host: <%= ENV['DATA_DB_HOST'] %>
  username: rails-app
  password: <%= ENV['RAILS-APP_DATABASE_PASSWORD'] %>

development:
  <<: *default
  database: rails_app

test:
  <<: *default
  database: rails_app

production:
  <<: *default
  database: rails_app
